# Generated by Django 4.2.4 on 2023-08-25 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nro_cliente', models.PositiveBigIntegerField(default=0)),
                ('nombre_apellido', models.CharField(default=False, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id_falla', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('1', 'conexion directa sin medidor'), ('2', 'conexion directa con medidor'), ('3', 'bajada pinchada'), ('4', 'neutro aislado'), ('5', 'bornera quemada'), ('6', 'sin precintos'), ('7', 'precintos cortados'), ('8', 'sin neutro'), ('9', 'medidor tumbado'), ('10', 'display apagado'), ('11', 'para normalizar'), ('12', 'medidor con agua'), ('13', 'puente entre fase'), ('14', 'carcasa rota'), ('15', 'conexion invertida'), ('16', 'medidor quemado'), ('17', 'medidor adulterado'), ('18', 'medidor frenado'), ('19', 'medidor parado'), ('20', 'integrador defasado')], default='1', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Fallas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nro_recibo', models.PositiveBigIntegerField()),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(blank=True, default='', max_length=150)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cliente')),
                ('falla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.falla')),
                ('pago', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.pago')),
            ],
            options={
                'verbose_name_plural': 'Trabajos',
            },
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id_suministro', models.AutoField(primary_key=True, serialize=False)),
                ('numero_suministro', models.SmallIntegerField(default=1)),
                ('direccion', models.CharField(max_length=40)),
                ('nro_medidor', models.PositiveIntegerField()),
                ('ruta', models.PositiveBigIntegerField()),
                ('localidad', models.CharField(choices=[('1', 'Resistencia'), ('2', 'Barranqueras'), ('3', 'Fontana'), ('5', 'Pto. Vilelas'), ('6', 'Colonia Benitez'), ('7', 'Margarita Belen')], default='1', max_length=1)),
                ('tarifa', models.CharField(choices=[('1', '00111'), ('2', '02A21'), ('3', '00112'), ('4', '00114')], default='1', max_length=1)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.cliente')),
            ],
            options={
                'verbose_name_plural': 'Suministros',
            },
        ),
    ]
